services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Edgar\Cron\Handler\:
        resource: "../../../lib/Handler/*"
        public: true

    Edgar\CronBundle\Service\:
        resource: "../../Service/*"
        public: true


